ci: update check workflow

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -52,6 +52,23 @@ jobs:
           anchor -V
           npm i -g pnpm
 
+        # Build
+      - name: Build
+        run: |
+          function build_and_test() {
+              local project=$1
+              echo "Building and Testing $project"
+              cd "$project" || return 1
+
+              # Run anchor build
+              if ! anchor build; then
+                  echo "::error::anchor build failed for $project"
+                  echo "$project: anchor build failed" >> $GITHUB_WORKSPACE/failed_projects.txt
+                  rm -rf target
+                  cd - > /dev/null
+                  return 1
+              fi
+          }
         # Run Clippy
       - name: Run Clippy
         run: cargo clippy --all-targets --all-features -- -D warnings
